name: server
services:
  caddy:
    image: caddy:alpine
    networks:
      internal: null
      web: null
    ports:
      - mode: ingress
        target: 80
        published: "80"
        protocol: tcp
      - mode: ingress
        target: 443
        published: "443"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /data/caddy/Caddyfile
        target: /etc/caddy/Caddyfile
        bind:
          create_host_path: true
      - type: bind
        source: /data/caddy/data
        target: /data
        bind:
          create_host_path: true
      - type: bind
        source: /data/caddy/config
        target: /config
        bind:
          create_host_path: true
networks:
  internal:
    name: server_internal
    driver: bridge
  web:
    name: web
    external: true
