name: build-trunk

on:
  push:
    branches: [ master, test-* ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
    - uses: actions/checkout@v2

    - name: Docker container test
      run: |
        cd server
        ./download-ccache.sh
        cp docker-compose.build-trunk.yml docker-compose.override.yml
        docker-compose up
