name: upload-ccache

on:
  push:
    branches: [ upload-ccache ]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 32768
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-docker-images: 'true'
          remove-codeql: 'true'

      - uses: actions/checkout@v4

      - name: Download ccache
        run: |
          ./download-ccache.sh
        working-directory: server

      - name: Build
        run: |
          cp docker-compose.build-all.yml docker-compose.override.yml
          sed -i 's/tail -f/cat/g' docker-entrypoint-build-all.sh
          docker-compose up 2>&1 | tee docker-compose.log
        working-directory: server

      - name: Print result
        run: |
          grep -B 100 -A 3 "Error 1" docker-compose.log || true
          ls data/crawl-master | xargs
        working-directory: server

      - name: Upload ccache
        run: |
          ./upload-ccache.sh "build-ccache (from Action)"
          ! grep -q "Error 1" docker-compose.log
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: server
